# Generated by Django 5.0 on 2024-01-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_versionproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versionproduct',
            options={'verbose_name': 'версия товара', 'verbose_name_plural': 'версии товара'},
        ),
    ]
