# Generated by Django 5.0 on 2024-01-09 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_versionproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='versionproduct',
            name='version_sign',
            field=models.BooleanField(default=True, verbose_name='признак текущей версии'),
        ),
    ]
