# Generated by Django 5.0 on 2024-01-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_versionproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionproduct',
            name='version_number',
            field=models.CharField(max_length=50, verbose_name='номер версии'),
        ),
    ]
