# Generated by Django 5.0 on 2024-01-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_options_product_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='autor',
            new_name='author',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Активна', 'Активна'), ('Не активна', 'Не активна')], default='Не активна', max_length=50, verbose_name='Статус'),
        ),
    ]
